# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP33",
  "description": "Датчик в гараже"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensor/2/
Content-Type: application/json

{
  "description": "Датчик в квартире"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensor/2/
Content-Type: application/json
